# Generated by Django 4.2.6 on 2023-10-23 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comunicado_modificado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='entidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.entidad'),
        ),
    ]
