# Generated by Django 4.2.6 on 2023-10-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='entidad',
            new_name='entidado',
        ),
    ]
