# Generated by Django 4.2.6 on 2023-10-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_entidad_user_entidado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
